#docker-compose.yml
version: "3.9"

services:
  flask-api:
    build: .
    container_name: flask_auth_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      #- ./siswa.db:/app/siswa.db # persist file SQLite
    restart: always
